/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quintaaulacursoemvideo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author Pedro
 */
public class TelaRelogio extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelogio
     */
    public TelaRelogio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagemCalendario = new javax.swing.JLabel();
        tituloDaAcao1 = new javax.swing.JLabel();
        botaoDataEHora = new javax.swing.JButton();
        visorDataEHora = new javax.swing.JLabel();
        tituloDaAcao2 = new javax.swing.JLabel();
        visorIdioma = new javax.swing.JLabel();
        tituloDaAcao3 = new javax.swing.JLabel();
        visorResolucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagemCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calendário imagem.png"))); // NOI18N

        tituloDaAcao1.setText("HORA E DATA ATUAL:");

        botaoDataEHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoDataEHora.setText("BOTÃO");
        botaoDataEHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDataEHoraActionPerformed(evt);
            }
        });

        visorDataEHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        visorDataEHora.setText("Clique no botão");

        tituloDaAcao2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tituloDaAcao2.setText("Idioma do Sistema:");

        visorIdioma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        visorIdioma.setText("Clique no botão");

        tituloDaAcao3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tituloDaAcao3.setText("Resolução da tela:");

        visorResolucao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        visorResolucao.setText("Clique no botão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imagemCalendario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloDaAcao1)
                            .addComponent(tituloDaAcao2)
                            .addComponent(tituloDaAcao3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visorDataEHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(visorResolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(visorIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoDataEHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloDaAcao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visorDataEHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tituloDaAcao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visorIdioma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tituloDaAcao3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visorResolucao))
                    .addComponent(imagemCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoDataEHora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDataEHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDataEHoraActionPerformed
        // TODO add your handling code here:
        Date relogio = new Date();
        visorDataEHora.setText(relogio.toString());
        Locale loc = Locale.getDefault();
        visorIdioma.setText("O idioma do sistema é " + loc.getDisplayLanguage());
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        visorResolucao.setText("A resolução do seu sistema é " + d.width + "X" + d.height);
    }//GEN-LAST:event_botaoDataEHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelogio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelogio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelogio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelogio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new TelaRelogio().setVisible(true);
                Calendar datado = Calendar.getInstance();
        int data = datado.get(Calendar.YEAR);
        //lblAA.setText(Integer.toString(data));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDataEHora;
    private javax.swing.JLabel imagemCalendario;
    private javax.swing.JLabel tituloDaAcao1;
    private javax.swing.JLabel tituloDaAcao2;
    private javax.swing.JLabel tituloDaAcao3;
    private javax.swing.JLabel visorDataEHora;
    private javax.swing.JLabel visorIdioma;
    private javax.swing.JLabel visorResolucao;
    // End of variables declaration//GEN-END:variables
}
